// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discord_guild_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getGuildSettings = `-- name: GetGuildSettings :one
SELECT id, guild_id, report_channel_id, set_by_user_id, created_at, updated_at FROM discord_guild_settings WHERE guild_id = $1 LIMIT 1
`

func (q *Queries) GetGuildSettings(ctx context.Context, guildID string) (DiscordGuildSetting, error) {
	row := q.db.QueryRow(ctx, getGuildSettings, guildID)
	var i DiscordGuildSetting
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ReportChannelID,
		&i.SetByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGuildSettings = `-- name: UpsertGuildSettings :one
INSERT INTO discord_guild_settings (id, guild_id, report_channel_id, set_by_user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
ON CONFLICT (guild_id) DO UPDATE
    SET report_channel_id = EXCLUDED.report_channel_id,
        set_by_user_id    = EXCLUDED.set_by_user_id,
        updated_at        = NOW()
RETURNING id, guild_id, report_channel_id, set_by_user_id, created_at, updated_at
`

type UpsertGuildSettingsParams struct {
	ID              uuid.UUID `json:"id"`
	GuildID         string    `json:"guild_id"`
	ReportChannelID string    `json:"report_channel_id"`
	SetByUserID     string    `json:"set_by_user_id"`
}

func (q *Queries) UpsertGuildSettings(ctx context.Context, arg UpsertGuildSettingsParams) (DiscordGuildSetting, error) {
	row := q.db.QueryRow(ctx, upsertGuildSettings,
		arg.ID,
		arg.GuildID,
		arg.ReportChannelID,
		arg.SetByUserID,
	)
	var i DiscordGuildSetting
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ReportChannelID,
		&i.SetByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
