// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discord_guilds.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const upsertDiscordGuild = `-- name: UpsertDiscordGuild :one
INSERT INTO discord_guilds (id, guild_id, guild_name, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (guild_id) DO UPDATE
    SET guild_name = EXCLUDED.guild_name,
        updated_at = NOW()
RETURNING id, guild_id, guild_name, created_at, updated_at
`

type UpsertDiscordGuildParams struct {
	ID        uuid.UUID `json:"id"`
	GuildID   string    `json:"guild_id"`
	GuildName string    `json:"guild_name"`
}

func (q *Queries) UpsertDiscordGuild(ctx context.Context, arg UpsertDiscordGuildParams) (DiscordGuild, error) {
	row := q.db.QueryRow(ctx, upsertDiscordGuild, arg.ID, arg.GuildID, arg.GuildName)
	var i DiscordGuild
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.GuildName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
