// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discord_registrations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDiscordRegistration = `-- name: GetDiscordRegistration :one
SELECT id, discord_user_id, discord_username, guild_id, guild_name, user_id, created_at, updated_at FROM discord_registrations WHERE discord_user_id = $1 AND guild_id = $2 LIMIT 1
`

type GetDiscordRegistrationParams struct {
	DiscordUserID string `json:"discord_user_id"`
	GuildID       string `json:"guild_id"`
}

func (q *Queries) GetDiscordRegistration(ctx context.Context, arg GetDiscordRegistrationParams) (DiscordRegistration, error) {
	row := q.db.QueryRow(ctx, getDiscordRegistration, arg.DiscordUserID, arg.GuildID)
	var i DiscordRegistration
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.DiscordUsername,
		&i.GuildID,
		&i.GuildName,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkDiscordRegistrationToUser = `-- name: LinkDiscordRegistrationToUser :exec
UPDATE discord_registrations SET user_id = $1, updated_at = NOW() WHERE discord_user_id = $2
`

type LinkDiscordRegistrationToUserParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	DiscordUserID string      `json:"discord_user_id"`
}

func (q *Queries) LinkDiscordRegistrationToUser(ctx context.Context, arg LinkDiscordRegistrationToUserParams) error {
	_, err := q.db.Exec(ctx, linkDiscordRegistrationToUser, arg.UserID, arg.DiscordUserID)
	return err
}

const listDiscordRegistrationsByUser = `-- name: ListDiscordRegistrationsByUser :many
SELECT id, discord_user_id, discord_username, guild_id, guild_name, user_id, created_at, updated_at FROM discord_registrations WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListDiscordRegistrationsByUser(ctx context.Context, userID pgtype.UUID) ([]DiscordRegistration, error) {
	rows, err := q.db.Query(ctx, listDiscordRegistrationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscordRegistration{}
	for rows.Next() {
		var i DiscordRegistration
		if err := rows.Scan(
			&i.ID,
			&i.DiscordUserID,
			&i.DiscordUsername,
			&i.GuildID,
			&i.GuildName,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDiscordRegistration = `-- name: UpsertDiscordRegistration :one
INSERT INTO discord_registrations (id, discord_user_id, discord_username, guild_id, guild_name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (discord_user_id, guild_id) DO UPDATE
    SET discord_username = EXCLUDED.discord_username,
        guild_name       = EXCLUDED.guild_name,
        updated_at       = NOW()
RETURNING id, discord_user_id, discord_username, guild_id, guild_name, user_id, created_at, updated_at
`

type UpsertDiscordRegistrationParams struct {
	ID              uuid.UUID `json:"id"`
	DiscordUserID   string    `json:"discord_user_id"`
	DiscordUsername string    `json:"discord_username"`
	GuildID         string    `json:"guild_id"`
	GuildName       string    `json:"guild_name"`
}

func (q *Queries) UpsertDiscordRegistration(ctx context.Context, arg UpsertDiscordRegistrationParams) (DiscordRegistration, error) {
	row := q.db.QueryRow(ctx, upsertDiscordRegistration,
		arg.ID,
		arg.DiscordUserID,
		arg.DiscordUsername,
		arg.GuildID,
		arg.GuildName,
	)
	var i DiscordRegistration
	err := row.Scan(
		&i.ID,
		&i.DiscordUserID,
		&i.DiscordUsername,
		&i.GuildID,
		&i.GuildName,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
