// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_codes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentVerificationCodesByUserID = `-- name: CountRecentVerificationCodesByUserID :one
SELECT COUNT(*) FROM email_verification_codes
WHERE user_id = $1 AND created_at > NOW() - INTERVAL '1 hour'
`

func (q *Queries) CountRecentVerificationCodesByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentVerificationCodesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStaleVerificationCodes = `-- name: DeleteStaleVerificationCodes :execrows
DELETE FROM email_verification_codes
WHERE (used_at IS NOT NULL AND used_at < NOW() - INTERVAL '7 days')
   OR (expires_at < NOW() - INTERVAL '1 day')
`

func (q *Queries) DeleteStaleVerificationCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleVerificationCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestUnusedVerificationCode = `-- name: GetLatestUnusedVerificationCode :one
SELECT id, user_id, code, expires_at, created_at, used_at FROM email_verification_codes
WHERE user_id = $1 AND used_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestUnusedVerificationCode(ctx context.Context, userID uuid.UUID) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, getLatestUnusedVerificationCode, userID)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const insertEmailVerificationCode = `-- name: InsertEmailVerificationCode :one
INSERT INTO email_verification_codes (id, user_id, code, expires_at, created_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, user_id, code, expires_at, created_at, used_at
`

type InsertEmailVerificationCodeParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertEmailVerificationCode(ctx context.Context, arg InsertEmailVerificationCodeParams) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, insertEmailVerificationCode,
		arg.ID,
		arg.UserID,
		arg.Code,
		arg.ExpiresAt,
	)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const markVerificationCodeUsed = `-- name: MarkVerificationCodeUsed :exec
UPDATE email_verification_codes SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkVerificationCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markVerificationCodeUsed, id)
	return err
}
