// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DiscordGuild struct {
	ID        uuid.UUID          `json:"id"`
	GuildID   string             `json:"guild_id"`
	GuildName string             `json:"guild_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DiscordGuildSetting struct {
	ID              uuid.UUID          `json:"id"`
	GuildID         string             `json:"guild_id"`
	ReportChannelID string             `json:"report_channel_id"`
	ChannelName     string             `json:"channel_name"`
	SetByUserID     string             `json:"set_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DiscordRegistration struct {
	ID              uuid.UUID          `json:"id"`
	DiscordUserID   string             `json:"discord_user_id"`
	DiscordUsername string             `json:"discord_username"`
	GuildID         string             `json:"guild_id"`
	GuildName       string             `json:"guild_name"`
	UserID          pgtype.UUID        `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type EmailVerificationCode struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type OauthIdentity struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Provider         string             `json:"provider"`
	ProviderUserID   string             `json:"provider_user_id"`
	ProviderUsername pgtype.Text        `json:"provider_username"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OauthToken struct {
	ID              uuid.UUID          `json:"id"`
	OauthIdentityID uuid.UUID          `json:"oauth_identity_id"`
	AccessTokenEnc  []byte             `json:"access_token_enc"`
	RefreshTokenEnc []byte             `json:"refresh_token_enc"`
	Scope           pgtype.Text        `json:"scope"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceName pgtype.Text        `json:"device_name"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	SetupProgress int32              `json:"setup_progress"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
