// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOAuthTokenByIdentity = `-- name: GetOAuthTokenByIdentity :one
SELECT id, oauth_identity_id, access_token_enc, refresh_token_enc, scope, expires_at, created_at, updated_at FROM oauth_tokens WHERE oauth_identity_id = $1 LIMIT 1
`

func (q *Queries) GetOAuthTokenByIdentity(ctx context.Context, oauthIdentityID uuid.UUID) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenByIdentity, oauthIdentityID)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.OauthIdentityID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthToken = `-- name: UpsertOAuthToken :one
INSERT INTO oauth_tokens (id, oauth_identity_id, access_token_enc, refresh_token_enc, scope, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
ON CONFLICT (oauth_identity_id) DO UPDATE
    SET access_token_enc  = EXCLUDED.access_token_enc,
        refresh_token_enc = EXCLUDED.refresh_token_enc,
        scope             = EXCLUDED.scope,
        expires_at        = EXCLUDED.expires_at,
        updated_at        = NOW()
RETURNING id, oauth_identity_id, access_token_enc, refresh_token_enc, scope, expires_at, created_at, updated_at
`

type UpsertOAuthTokenParams struct {
	ID              uuid.UUID          `json:"id"`
	OauthIdentityID uuid.UUID          `json:"oauth_identity_id"`
	AccessTokenEnc  []byte             `json:"access_token_enc"`
	RefreshTokenEnc []byte             `json:"refresh_token_enc"`
	Scope           pgtype.Text        `json:"scope"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, upsertOAuthToken,
		arg.ID,
		arg.OauthIdentityID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.OauthIdentityID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
