// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_identities.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (id, user_id, provider, provider_user_id, provider_username, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, user_id, provider, provider_user_id, provider_username, created_at, updated_at
`

type CreateOAuthIdentityParams struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	Provider         string      `json:"provider"`
	ProviderUserID   string      `json:"provider_user_id"`
	ProviderUsername pgtype.Text `json:"provider_username"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderUsername,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthIdentity = `-- name: DeleteOAuthIdentity :exec
DELETE FROM oauth_identities WHERE id = $1
`

func (q *Queries) DeleteOAuthIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthIdentity, id)
	return err
}

const getOAuthIdentityByProviderUserID = `-- name: GetOAuthIdentityByProviderUserID :one
SELECT id, user_id, provider, provider_user_id, provider_username, created_at, updated_at FROM oauth_identities WHERE provider = $1 AND provider_user_id = $2 LIMIT 1
`

type GetOAuthIdentityByProviderUserIDParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthIdentityByProviderUserID(ctx context.Context, arg GetOAuthIdentityByProviderUserIDParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityByProviderUserID, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthIdentityByUserAndProvider = `-- name: GetOAuthIdentityByUserAndProvider :one
SELECT id, user_id, provider, provider_user_id, provider_username, created_at, updated_at FROM oauth_identities WHERE user_id = $1 AND provider = $2 LIMIT 1
`

type GetOAuthIdentityByUserAndProviderParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetOAuthIdentityByUserAndProvider(ctx context.Context, arg GetOAuthIdentityByUserAndProviderParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityByUserAndProvider, arg.UserID, arg.Provider)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthIdentitiesByUser = `-- name: ListOAuthIdentitiesByUser :many
SELECT id, user_id, provider, provider_user_id, provider_username, created_at, updated_at FROM oauth_identities WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListOAuthIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]OauthIdentity, error) {
	rows, err := q.db.Query(ctx, listOAuthIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthIdentity{}
	for rows.Next() {
		var i OauthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.ProviderUsername,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
